#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-or-later
//
// The web app's strings are the Android app's: the same words in the same six
// languages, from app/src/main/res/values*/strings.xml. This writes the ones
// the web sources ask for (t("key"), t("key", ...)) as a Kotlin file, so the
// bundle carries what it uses and nothing else. A key the web asks for that
// does not exist is an error here, not a blank on a screen.
//
//   node tools/web/strings.mjs <web sources dir> <output .kt file>

import { readdirSync, readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';

const [, , sourcesDir, outFile] = process.argv;
const RES = 'app/src/main/res';

const walk = (dir) => readdirSync(dir).flatMap((f) => {
  const p = join(dir, f);
  return statSync(p).isDirectory() ? walk(p) : p.endsWith('.kt') ? [p] : [];
});

// Every string literal of the web sources that is the name of an Android string: t("key") calls, and
// keys held in a table or an enum (Tab.ADD("tab_add")). A literal that merely looks like a key costs a line.
const literals = new Set();
const asked = new Set();
for (const file of walk(sourcesDir)) {
  if (file.endsWith('GeneratedStrings.kt')) continue;
  const text = readFileSync(file, 'utf8');
  for (const m of text.matchAll(/\bt\("([a-z0-9_]+)"/g)) asked.add(m[1]);
  for (const m of text.matchAll(/"([a-z][a-z0-9_]*)"/g)) literals.add(m[1]);
}

const unescape = (s) => s
  .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'")
  .replace(/&amp;/g, '&')
  .replace(/\\'/g, "'").replace(/\\"/g, '"').replace(/\\n/g, '\n').replace(/\\@/g, '@').replace(/\\\?/g, '?')
  .replace(/\\u([0-9a-fA-F]{4})/g, (_, h) => String.fromCharCode(parseInt(h, 16)));

const read = (dir) => {
  const xml = readFileSync(join(RES, dir, 'strings.xml'), 'utf8');
  const out = new Map();
  for (const m of xml.matchAll(/<string name="([^"]+)"[^>]*>([\s\S]*?)<\/string>/g)) out.set(m[1], unescape(m[2]));
  return out;
};

const kt = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$').replace(/\n/g, '\\n') + '"';

const languages = { en: 'values', es: 'values-es', de: 'values-de', fr: 'values-fr', it: 'values-it', pt: 'values-pt' };
const tables = Object.fromEntries(Object.entries(languages).map(([code, dir]) => [code, read(dir)]));

const wanted = new Set([...asked, ...[...literals].filter((k) => tables.en.has(k))]);
const missing = [...asked].filter((k) => !tables.en.has(k));
if (missing.length) {
  console.error(`strings: the web asks for strings Android does not have: ${missing.join(', ')}`);
  process.exit(1);
}

let out = '// SPDX-License-Identifier: GPL-3.0-or-later\n// Generated by tools/web/strings.mjs from the Android string resources. Do not edit.\npackage io.github.sirallap.fulla.web\n\n';
out += 'internal val GENERATED_STRINGS: Map<String, Map<String, String>> = mapOf(\n';
for (const code of Object.keys(languages)) {
  out += `    ${kt(code)} to mapOf(\n`;
  for (const key of [...wanted].sort()) out += `        ${kt(key)} to ${kt(tables[code].get(key) ?? tables.en.get(key))},\n`;
  out += '    ),\n';
}
out += ')\n';
mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out);
console.log(`strings: ${wanted.size} strings in ${Object.keys(languages).length} languages`);
